export const DOCUMENT_TYPE_VALUES = [
  'ALLGEMEIN',
  'VERTRAG',
  'ANGEBOT',
  'AUFTRAG',
  'RECHNUNG',
  'GUTSCHRIFT',
  'LIEFERSCHEIN',
  'PROTOKOLL',
  'ABNAHME',
  'BERICHT',
  'KORRESPONDENZ',
  'FOTO',
  'PLAN_ZEICHNUNG',
  'CHECKLISTE',
  'SICHERHEITSDOKUMENT',
  'ZERTIFIKAT_NACHWEIS',
  'BEDIENUNGSANLEITUNG',
  'WARTUNG_SERVICE',
  'STUNDENZETTEL',
] as const;

export const LEGACY_DOCUMENT_TYPE_VALUES = ['PROJEKTDOKUMENT'] as const;

export const VALID_DOCUMENT_TYPE_VALUES = [
  ...DOCUMENT_TYPE_VALUES,
  ...LEGACY_DOCUMENT_TYPE_VALUES,
] as const;

export type DocumentTypeValue = (typeof VALID_DOCUMENT_TYPE_VALUES)[number];
